
export const overallData = [
    {
        id: 1,
        image: 'https://img.naukimg.com/logo_images/groups/v1/359414.gif',
        subheading: 'Leading Indian Firm in IT Domain',
        title: 'React Js Developer',
        company_type1: 'Indian MNC',
        company_type2: 'Service',
        rating: 4.3,
        experiences: '0-5 yrs',
        openings: 5,
        location: 'Coimbatore',
        skill: ['RDBMS', 'Javascript', 'Development', 'Node.Js', 'API', 'Java', 'Data', 'HTML'],
        salary: '3.5-4.5LPA',
        time: '3 days ago',
        job_highlights: ['Job highlights', 'The candidate should possess a positive attitude,be a team player,and have a thirst for learning new technologies', 'Learn new technologies as required', 'Preferred Skills'],
        job_description: 'We are seeking a highly motivated and enthusiastic software developer to join our team. The successful candidate will be responsible for writing code, maintaining and updating existing software systems, and providing technical support for our clients. The candidate should possess a positive attitude, be a team player, and have a thirst for learning new technologies.',
        responsibilities: ['Write clean', 'efficient', 'and maintainable code', 'Maintain and update existing software systems', 'Troubleshoot and debug code', 'Collaborate with cross-functional teams to develop software solutions', 'Provide technical support to clients', 'Learn new technologies as required'],
        requirements: [`Bachelor's degree in computer science or related field`, `Ability to code in at least one of the following programming languages: Python`, `Javascript, Kotlin or Swift,Good communication skills and fluency in English`, `Positive attitude and team player mentality,Ability to work in an office setting`],
        employmentType: ['workFromOffice', 'Work from Office', 'Remote'],
        role: "Front End Developer",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        roleCategory: "Software Development",
        education: 'Any Graduate',
        about_company: "Testpress is India's fastest growing e-learning platform which helps students prepare for competitive exams effectively. We collaborate with various coaching organizations and act as a platform to connect students with their materials. We think big, start small, and scale fast. We like to find problems and fix them 'the right way'. Most importantly we don't fear creating constructive disruption.",
        company_info: ['https://www.testpress.tech', '113/1, Door No. 1, Second floor, Block B1, Radial Road (Opp. to ABS thirumana mahal, Tiruthani Nagar, Old Pallavaram, Chennai, Tamil Nadu 600117.'],

    },
    {
        id: 2,
        image: 'https://img.naukri.com/logo_images/v3/1959274.gif',
        subheading: 'Tech Innovator Solutions',
        title: 'Data Scientist',
        company_type1: 'Global Tech ',
        company_type2: 'Product',
        rating: '4.8',
        experiences: '6-10 yrs',
        openings: 13,
        location: 'Hyderabad',
        skill: ['Machine Learning', 'Python', 'Data Analysis', 'Statistics', 'SQL', 'Big Data', 'TensorFlow'],
        salary: '6-10LPA',
        time: '1 day ago',
        job_highlights: ['Job highlights', 'Exciting opportunity to work on cutting-edge projects', 'Collaborate with top-tier professionals in the industry', 'Contribute to the development of groundbreaking technologies'],
        job_description: 'We are looking for a skilled Data Scientist to join our dynamic team. The ideal candidate will have a strong background in machine learning, data analysis, and statistical modeling. Responsibilities include analyzing large datasets, developing predictive models, and contributing to the advancement of innovative technologies.',
        responsibilities: ['Analyze and interpret complex data sets', 'Develop and implement machine learning models', 'Collaborate with cross-functional teams on data-driven projects', 'Stay updated on the latest trends in data science and machine learning', 'Contribute to the development of innovative solutions'],
        requirements: ['Master\'s or Ph.D. in Computer Science, Statistics, or a related field', 'Proven experience in machine learning and data analysis', 'Proficiency in Python and relevant libraries (e.g., pandas, scikit-learn)', 'Strong analytical and problem-solving skills', 'Excellent communication and presentation abilities'],
        employmentType: ['workFromOffice', 'Remote'],
        role: "Data Scientist",
        industryType: "Advertising & Marketing",
        department: "Data Science & Analytics",
        roleCategory: "Data Science & Machine Learning",
        education: 'Master\'s or Ph.D. in Computer Science, Statistics, or related field',
        about_company: 'InnovateTech Solutions is a global leader in providing cutting-edge technology solutions to address complex challenges. We foster a culture of innovation and collaboration, empowering our employees to push the boundaries of what\'s possible. Join us in shaping the future of technology!',
        company_info: ['https://www.innovatetechsolutions.com', '123 Tech Park Lane, Electronic City, Bangalore - 560001']
    },
    {
        id: 3,
        image: 'https://img.naukimg.com/logo_images/groups/v1/2861454.gif',
        subheading: 'Enterprise Java Technologies',
        title: 'UX/UI Designer',
        company_type1: 'Design Agency',
        company_type2: 'Service',
        rating: '4.5',
        experiences: '0-5 yrs',
        openings: 5,
        location: 'Pune',
        skill: ["jQuery", "Illustrator", "HTML5", "HTML", "Photoshop", "Android", "CSS3"],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Opportunity to shape the visual identity of cutting-edge projects', 'Collaborate with a talented and diverse design team', 'Contribute to user-centered design solutions'],
        job_description: 'We are seeking a passionate and creative UX/UI Designer to join our design studio. The ideal candidate should have a strong portfolio showcasing their expertise in user experience and interface design. Responsibilities include collaborating with cross-functional teams, creating wireframes, and designing visually appealing and user-friendly interfaces.',
        responsibilities: ['Create wireframes, prototypes, and high-fidelity designs', 'Collaborate with product managers and developers to implement design solutions', 'Conduct user research and usability testing', 'Stay updated on industry trends and best practices', 'Communicate design concepts and ideas effectively'],
        requirements: ['Bachelor\'s degree in Design, HCI, or related field', 'Proven experience in UX/UI design', 'Proficiency in design tools such as Adobe XD, Sketch, or Figma', 'Strong understanding of user-centered design principles', 'Excellent communication and collaboration skills'],
        employmentType: ['Work from Home', 'workFromOffice'],
        role: "UI / UX Designer",
        industryType: "Internet",
        department: "UX, Design & Architecture",
        roleCategory: "UI / UX",
        education: 'Bachelor\'s degree in Design, HCI, or related field',
        about_company: 'DesignCraft Studios is a leading design agency committed to delivering innovative and user-centric design solutions. We believe in the power of design to transform businesses and enhance user experiences. Join us in shaping the visual landscape of tomorrow!',
        company_info: ['https://www.designcraftstudios.com', '456 Design Avenue, Creative City, Mumbai - 400001']
    },
    {
        id: 4,
        image: 'https://img.naukri.com/logo_images/v3/1959274.gif',
        subheading: 'Tech Innovator Solutions',
        title: 'Full Stack Developer',
        company_type1: 'Technology Solutions Provider',
        company_type2: 'product',
        rating: '4.7',
        experiences: '6-10 yrs',
        openings: 22,
        location: 'Delhi',
        skill: ['PHP', 'Laravel', 'Flutter', 'Firebase', 'Gateway Integration', 'html/css', 'Payment Gateways'],
        salary: '15-25LPA',
        time: '1 day ago',
        job_highlights: [
            'Job highlights',
            'Lead the design and implementation of scalable cloud solutions',
            'Collaborate with global clients on innovative technology projects',
            'Shape the future of cloud computing'
        ],
        job_description: 'Tech Innovator Solutions is looking for an experienced Full Stack Developer to join our dynamic team. The ideal candidate will have a strong background in full stack development and expertise in cloud solutions architecture. Responsibilities include leading the design and implementation of scalable cloud solutions, collaborating with cross-functional teams, and providing technical expertise in cloud-based projects.',
        responsibilities: [
            'Lead the design and implementation of scalable cloud solutions',
            'Collaborate with cross-functional teams on cloud-based projects',
            'Provide technical expertise in cloud architecture and best practices',
            'Conduct assessments and recommend optimizations for existing cloud deployments',
            'Stay updated on emerging trends in cloud computing'
        ],
        requirements: [
            'Bachelor\'s or Master\'s degree in Computer Science or related field',
            'Proven experience in full stack development and cloud architecture',
            'Certifications in AWS, Azure, or Google Cloud',
            'Experience with DevOps practices and tools',
            'Excellent communication and client-facing skills'
        ],
        employment_type: 'Full Time, Permanent',
        role: "Full Stack Developer",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['workFromOffice', 'Remote'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Tech Innovator Solutions is a leading technology solutions provider, specializing in full stack development, cloud computing, digital transformation, and innovation. Join us in shaping the future of technology by delivering cutting-edge solutions to our global clientele.',
        company_info: ['https://techinnovatorsolutions.com', '789 Innovation Street, Tech City, Bangalore - 560002']
    },
    {
        id: 5,
        image: 'https://img.naukri.com/logo_images/v3/3790422.gif',
        subheading: 'Innovations Tech',
        title: 'HealthTech Software Engineer',
        company_type1: 'Healthcare Technology Firm',
        company_type2: 'Service',
        rating: '4.6',
        experiences: '0-5 yrs',
        openings: 7,
        location: 'Delhi',
        skill: ['T-SQL', 'SQL Server Development', 'TDE', 'Microsoft SQL Server', 'Transparent Data'],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Contribute to the development of cutting-edge healthcare solutions', 'Collaborate with medical professionals on innovative projects', 'Make a meaningful impact on the healthcare industry'],
        job_description: 'Innovative Health Technologies is seeking a skilled HealthTech Software Engineer to join our team. The ideal candidate will have a strong background in healthcare IT, with experience in developing software solutions for the healthcare industry. Responsibilities include working on Electronic Health Records (EHR) systems, medical imaging software, and integrating healthcare standards such as HL7 and FHIR.',
        responsibilities: ['Develop and maintain healthcare software applications', 'Collaborate with medical professionals and IT teams on project requirements', 'Implement and integrate Electronic Health Records (EHR) systems', 'Work on medical imaging software development', 'Ensure compliance with healthcare data standards'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in healthcare IT and software development', 'Proficiency in Java, Python, or related languages', 'Familiarity with healthcare standards such as HL7 and FHIR', 'Strong problem-solving and collaboration skills'],
        role: "Full Stack Developer",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['Work from Home', 'workFromOffice', 'Remote'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Innovative Health Technologies is at the forefront of revolutionizing healthcare through innovative technology solutions. Join our mission to make a positive impact on patient care and contribute to the advancement of healthcare IT.',
        company_info: ['https://innovativehealthtech.com', '567 Health Drive, MedTech City, New Delhi - 110001']
    },
    {
        id: 6,
        image: 'https://img.naukimg.com/logo_images/groups/v1/359414.gif',
        subheading: 'Leading Indian Firm in IT Domain',
        title: 'Senior Financial Analyst',
        company_type1: 'Financial Services',
        company_type2: 'Service',
        rating: '4.9',
        experiences: '6-10 yrs',
        openings: 19,
        location: 'Bangalore',
        skill: ['Business Administration', 'Data Validation', 'Interpersonal Skills', 'Financial Reporting'],
        salary: '10-15LPA',
        time: '1 day ago',
        job_highlights: ['Job highlights', 'Lead financial planning and analysis initiatives', 'Collaborate with executive leadership on strategic financial decisions', 'Contribute to the financial success of a dynamic financial services firm'],
        job_description: 'Smart Finance Corporation is seeking a highly skilled Senior Financial Analyst to join our finance team. The ideal candidate will have extensive experience in financial analysis, budgeting, and forecasting. Responsibilities include leading financial modeling projects, providing insights to executive leadership, and ensuring the financial health of the organization.',
        responsibilities: ['Lead financial planning and analysis activities', 'Develop and maintain complex financial models', 'Collaborate with various departments to gather financial data', 'Conduct variance analysis and provide recommendations', 'Contribute to the development of financial strategies'],
        requirements: ['Bachelor\'s or Master\'s degree in Finance, Accounting, or related field', 'Proven experience as a Senior Financial Analyst', 'Advanced proficiency in Excel and financial modeling tools', 'Strong analytical and problem-solving skills', 'Excellent communication and presentation abilities'],
        role: "Financial Analyst",
        industryType: "Management Consulting",
        department: "Finance & Accounting",
        employmentType: ['workFromOffice', 'Remote'],
        roleCategory: "Analyst",
        education: 'Bachelor\'s or Master\'s degree in Finance, Accounting, or related field',
        about_company: 'Smart Finance Corporation is a leading financial services firm committed to providing innovative solutions to clients. Join us in shaping the financial landscape and contributing to the success of our dynamic and growing organization.',
        company_info: ['https://smartfinancecorp.com', '789 Financial Street, Fintech Square, Mumbai - 400005']
    },
    {
        id: 7,
        image: 'https://img.naukimg.com/logo_images/groups/v1/2861454.gif',
        subheading: 'Enterprise Java Technologies',
        title: 'Python Developer',
        company_type1: 'Renewable Energy',
        company_type2: 'Service',
        rating: '4.5',
        experiences: '6-10 yrs',
        openings: 3,
        location: 'Chennai',
        skill: ['Python', 'Django', 'Flask', 'RESTful APIs', 'SQL', 'Git', 'Test-Driven Development'],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Contribute to the development of sustainable energy solutions', 'Work on cutting-edge projects in the renewable energy sector', 'Play a key role in advancing green technologies'],
        job_description: 'Green Energy Technologies is seeking a passionate Renewable Energy Engineer to join our team. The ideal candidate will have a strong background in renewable energy systems, with experience in solar and wind power projects. Responsibilities include engineering design, project management, and ensuring the successful implementation of sustainable energy solutions.',
        responsibilities: ['Design and implement renewable energy systems', 'Collaborate with cross-functional teams on green energy projects', 'Conduct feasibility studies and assess energy efficiency', 'Manage and oversee renewable energy projects', 'Stay updated on the latest trends in sustainable technologies'],
        requirements: ['Bachelor\'s or Master\'s degree in Renewable Energy, Engineering, or related field', 'Proven experience in renewable energy projects', 'Knowledge of solar and wind power technologies', 'Project management skills', 'Passion for sustainability and green technologies'],
        role: "Mechanical Engineer",
        industryType: "Power",
        department: "Production, Manufacturing & Engineering",
        employmentType: ['workFromOffice', 'workFromHome'],
        roleCategory: "Engineering",
        education: 'Bachelor\'s or Master\'s degree in Renewable Energy, Engineering, or related field',
        about_company: 'Green Energy Technologies is a pioneer in developing innovative and sustainable solutions for the renewable energy sector. Join us in making a positive impact on the environment and contributing to a greener and cleaner future.',
        company_info: ['https://greenenergytech.com', '456 Eco Lane, Sustainable City, Chennai - 600010']
    },
    {
        id: 8,
        image: 'https://img.naukri.com/logo_images/v3/1959274.gif',
        subheading: 'Tech Innovator Solutions',
        title: 'Agricultural Data Scientist',
        company_type1: 'Agriculture Technology',
        company_type2: 'Product',
        rating: '4.6',
        experiences: '11-15 yrs',
        openings: 8,
        location: 'Bangalore',
        skill: ['Cloud Computing', 'C++', 'Data Analysis', 'Data Modeling', 'Agile', 'Data Structures'],
        salary: '15-25LPA',
        time: '1 day ago',
        job_highlights: ['Job highlights', 'Apply data science to enhance precision agriculture techniques', 'Collaborate on innovative projects at the intersection of agriculture and technology', 'Contribute to sustainable and efficient farming practices'],
        job_description: 'AgriTech Innovators is seeking an Agricultural Data Scientist to join our team. The ideal candidate will have a strong background in data science, machine learning, and a keen interest in applying these skills to agriculture. Responsibilities include developing predictive models, analyzing agricultural data, and contributing to the advancement of precision farming techniques.',
        responsibilities: ['Apply data science techniques to analyze agricultural data', 'Develop and implement machine learning models for crop prediction', 'Collaborate with agronomists and scientists on research projects', 'Utilize IoT and remote sensing technologies in agriculture', 'Contribute to the development of sustainable farming practices'],
        requirements: ['Bachelor\'s or Master\'s degree in Data Science, Agriculture, or related field', 'Proven experience in data science and machine learning', 'Familiarity with precision agriculture concepts', 'Proficiency in Python and relevant data science tools', 'Passion for applying technology to agriculture'],
        role: "Data Scientist",
        industryType: "Advertising & Marketing",
        department: "Data Science & Analytics",
        employmentType: ['workFromOffice', 'workFromHome'],
        roleCategory: "Data Science & Machine Learning",
        education: 'Bachelor\'s or Master\'s degree in Data Science, Agriculture, or related field',
        about_company: 'AgriTech Innovators is at the forefront of revolutionizing agriculture through technology. Join our team to contribute to sustainable farming practices and make a positive impact on the future of agriculture.',
        company_info: ['https://agritechinnovators.com', '789 FarmTech Lane, AgriCity, Pune - 411005']
    },
    {
        id: 9,
        image: 'https://img.naukimg.com/logo_images/groups/v1/4587239.gif',
        subheading: 'Code Experts',
        title: 'Educational Content Developer',
        company_type1: 'EdTech',
        company_type2: 'Product',
        rating: '4.8',
        experiences: '6-10 yrs',
        openings: 5,
        location: 'Bangalore',
        skill: ['Chemistry', 'Digital Content', 'Zoology', 'Botany', 'PowerPoint Presentation'],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Create engaging and effective educational content', 'Collaborate with educators and subject matter experts', 'Contribute to shaping the future of education through innovative content'],
        job_description: 'Smart Education Hub is looking for an experienced Educational Content Developer to join our EdTech team. The ideal candidate will have a strong background in curriculum design, e-learning, and instructional design. Responsibilities include creating engaging educational content, collaborating with educators, and utilizing innovative technologies to enhance the learning experience.',
        responsibilities: ['Develop and design educational content for various subjects', 'Collaborate with subject matter experts and educators', 'Utilize e-learning platforms and technologies', 'Create engaging multimedia content, including videos and interactive materials', 'Ensure alignment with curriculum standards and educational goals'],
        requirements: ['Bachelor\'s or Master\'s degree in Education, Instructional Design, or related field', 'Proven experience in educational content development', 'Familiarity with learning management systems', 'Strong creative and collaborative skills', 'Passion for improving education through technology'],
        role: "Mechanical Engineer",
        industryType: "Power",
        department: "Production, Manufacturing & Engineering",
        employmentType: ['workFromOffice', 'workFromHome'],
        roleCategory: "Engineering",
        education: 'Bachelor\'s or Master\'s degree in Education, Instructional Design, or related field',
        about_company: 'Smart Education Hub is dedicated to transforming education through innovative technology and engaging content. Join our team to be a part of the educational revolution and contribute to shaping the future of learning.',
        company_info: ['https://smarteducationhub.com', '567 Learning Street, EduCity, Delhi - 110020']
    },
    {
        id: 10,
        image: 'https://img.naukimg.com/logo_images/groups/v1/2861454.gif',
        subheading: 'Enterprise Java Technologies',
        title: 'Frontend Developer (web developer)',
        company_type1: 'Technology Solutions',
        company_type2: 'Service',
        rating: '4.8',
        experiences: '0-5 yrs',
        openings: 7,
        location: 'Chennai',
        skill: ['HTML', 'CSS', 'JavaScript', 'React', 'Vue.js', 'Responsive Web Design', 'UI/UX Design'],
        salary: '3-6LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Shape the user interface of cutting-edge web applications', 'Collaborate with designers and backend developers on dynamic projects', 'Contribute to creating seamless and responsive user experiences'],
        job_description: 'Frontend Innovators is looking for a skilled Frontend Developer to join our dynamic team. The ideal candidate will have a strong proficiency in HTML, CSS, and JavaScript, along with experience in popular frontend frameworks like React and Vue.js. Responsibilities include collaborating with designers and backend developers to create visually appealing and user-friendly web applications.',
        responsibilities: ['Develop and implement user interfaces for web applications', 'Collaborate with designers to create responsive and visually appealing designs', 'Integrate frontend components with backend systems', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in frontend development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in frontend development', 'Proficiency in HTML, CSS, and JavaScript', 'Experience with frontend frameworks such as React or Vue.js', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['workFromOffice', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Frontend Innovators is a leading technology solutions provider, specializing in creating innovative and user-centric frontend experiences. Join our team to contribute to shaping the digital landscape through cutting-edge frontend development.',
        company_info: ['https://frontendinnovators.com', '456 Tech Street, WebCity, Bangalore - 560005']
    },
    {
        id: 11,
        image: 'https://img.naukimg.com/logo_images/groups/v1/359414.gif',
        subheading: 'Leading Indian Firm in IT Domain',
        title: 'Frontend Developer (web) ',
        company_type1: 'Technology Solutions',
        company_type2: 'Service',
        rating: '4.8',
        experiences: '6-10 yrs',
        openings: 33,
        location: 'Pune',
        skill: ['HTML', 'CSS', 'JavaScript', 'React', 'Vue.js', 'Responsive Web Design', 'UI/UX Design'],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Shape the user interface of cutting-edge web applications', 'Collaborate with designers and backend developers on dynamic projects', 'Contribute to creating seamless and responsive user experiences'],
        job_description: 'Frontend Innovators is looking for a skilled Frontend Developer to join our dynamic team. The ideal candidate will have a strong proficiency in HTML, CSS, and JavaScript, along with experience in popular frontend frameworks like React and Vue.js. Responsibilities include collaborating with designers and backend developers to create visually appealing and user-friendly web applications.',
        responsibilities: ['Develop and implement user interfaces for web applications', 'Collaborate with designers to create responsive and visually appealing designs', 'Integrate frontend components with backend systems', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in frontend development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in frontend development', 'Proficiency in HTML, CSS, and JavaScript', 'Experience with frontend frameworks such as React or Vue.js', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['workFromOffice', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Frontend Innovators is a leading technology solutions provider, specializing in creating innovative and user-centric frontend experiences. Join our team to contribute to shaping the digital landscape through cutting-edge frontend development.',
        company_info: ['https://frontendinnovators.com', '456 Tech Street, WebCity, Bangalore - 560005']
    },
    {
        id: 12,
        image: 'https://img.naukri.com/logo_images/v3/1959274.gif',
        subheading: 'Tech Innovator Solutions',
        title: 'Python Developer',
        company_type1: 'Technology Solutions',
        company_type2: 'Product',
        rating: '4.9',
        experiences: '15-25 yrs',
        openings: 45,
        location: 'Delhi',
        skill: ['Python', 'Django', 'Flask', 'RESTful APIs', 'SQL', 'Git', 'Test-Driven Development'],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Develop and maintain scalable Python applications', 'Collaborate with cross-functional teams on diverse projects', 'Contribute to designing and implementing RESTful APIs'],
        job_description: 'Python Innovate Solutions is looking for a skilled Python Developer to join our team. The ideal candidate will have expertise in Python, Django, and Flask, with a passion for building scalable and efficient applications. Responsibilities include collaborating with cross-functional teams, designing and implementing RESTful APIs, and ensuring the quality of code through test-driven development.',
        responsibilities: ['Develop and maintain scalable Python applications', 'Collaborate with frontend and backend developers on project requirements', 'Design and implement RESTful APIs for application integration', 'Utilize version control systems, especially Git', 'Write unit tests and participate in test-driven development practices'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in Python development', 'Expertise in Django and Flask frameworks', 'Experience with SQL databases', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime', 'workFromOffice', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Python Innovate Solutions is at the forefront of delivering innovative solutions using Python technology. Join our team to contribute to the development of cutting-edge applications and shape the future of Python development.',
        company_info: ['https://pythoninnovate.com', '567 Python Street, CodeCity, Delhi - 110012']
    },
    {
        id: 13,
        image: 'https://img.naukri.com/logo_images/v3/3790422.gif',
        subheading: 'Innovations Tech',
        title: 'Java Developer',
        company_type1: 'Technology Solutions',
        company_type2: 'Service',
        rating: '4.8',
        openings: 20,
        experiences: '25-50 yrs',
        location: 'Hyderabad',
        skill: ['Java', 'Spring Framework', 'Hibernate', 'RESTful APIs', 'Maven', 'Microservices Architecture', 'Jenkins'],
        salary: '10-15LPA',
        time: '1 day ago',
        job_highlights: ['Job highlights', 'Develop and maintain enterprise-level Java applications', 'Collaborate with cross-functional teams on diverse projects', 'Contribute to the design and implementation of microservices architecture'],
        job_description: 'Java Innovations Tech is seeking an experienced Java Developer to join our dynamic team. The ideal candidate will have expertise in Java, Spring Framework, and Hibernate, with a focus on building scalable and robust enterprise-level applications. Responsibilities include collaborating with cross-functional teams, designing RESTful APIs, and contributing to the implementation of microservices architecture.',
        responsibilities: ['Develop and maintain enterprise-level Java applications', 'Collaborate with frontend and backend developers on project requirements', 'Design and implement RESTful APIs for application integration', 'Utilize build tools such as Maven', 'Contribute to the implementation of microservices architecture'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in Java development', 'Expertise in Spring Framework and Hibernate', 'Experience with RESTful APIs and microservices architecture', 'Familiarity with Jenkins for continuous integration'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime', 'workFromOffice', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Java Innovations Tech is a technology-driven company committed to delivering high-quality solutions using Java technology. Join our team to contribute to the development of enterprise-level applications and shape the future of Java development.',
        company_info: ['https://javainnovations.com', '789 Java Avenue, CodeHub City, Bangalore - 560010']
    },
    {
        id: 14,
        image: 'https://img.naukimg.com/logo_images/groups/v1/4587239.gif',
        subheading: 'Code Experts',
        title: 'Senior Java Software Engineer',
        company_type1: 'Software Development',
        company_type2: 'Product',
        rating: '4.9',
        experiences: '6-10 yrs',
        openings: 15,
        location: 'Mumbai',
        skill: ['Java', 'Spring Boot', 'Microservices', 'Kafka', 'Docker', 'MySQL', 'JUnit'],
        salary: '15-25LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Lead the design and development of Java-based software solutions', 'Collaborate with cross-functional teams on complex projects', 'Contribute to building scalable and high-performance applications'],
        job_description: 'Java Code Experts is looking for a Senior Java Software Engineer to join our experienced team. The ideal candidate will have a deep understanding of Java, Spring Boot, and microservices architecture. Responsibilities include leading the design and development of complex software solutions, collaborating with cross-functional teams, and contributing to the creation of scalable and high-performance applications.',
        responsibilities: ['Lead the design and development of Java-based software solutions', 'Collaborate with frontend and backend teams on project requirements', 'Implement microservices architecture with technologies like Kafka and Docker', 'Ensure code quality through unit testing using tools like JUnit', 'Contribute to architectural decisions and optimizations'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Extensive experience in Java development', 'Expertise in Spring Boot and microservices architecture', 'Knowledge of database systems, especially MySQL', 'Experience with containerization using Docker', 'Strong problem-solving and leadership skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Java Code Experts is a software development company known for delivering robust and scalable solutions using Java technology. Join our team to lead the development of innovative software solutions and make an impact in the world of Java development.',
        company_info: ['https://javacodeexperts.com', '567 Code Street, JavaTech City, Mumbai - 400012']
    },
    {
        id: 15,
        image: 'https://img.naukimg.com/logo_images/groups/v1/2861454.gif',
        subheading: 'Enterprise Java Technologies',
        title: 'Java Full Stack Developer',
        company_type1: 'Software Development',
        company_type2: 'Service',
        rating: '4.8 yrs',
        openings: 37,
        experiences: '26-30 yrs',
        location: 'Chennai',
        skill: ['Java', 'Spring Boot', 'Angular', 'RESTful APIs', 'Hibernate', 'MySQL', 'HTML/CSS'],
        salary: '25-50LPA',
        time: '1 day ago',
        job_highlights: ['Job highlights', 'Work on end-to-end development of Java-based full-stack applications', 'Collaborate with frontend and backend teams for seamless integration', 'Contribute to creating modern and responsive user interfaces'],
        job_description: 'Enterprise Java Technologies is seeking a skilled Java Full Stack Developer to join our dynamic team. The ideal candidate will have expertise in Java, Spring Boot, and frontend technologies like Angular. Responsibilities include working on the end-to-end development of full-stack applications, collaborating with cross-functional teams, and contributing to the creation of modern and responsive user interfaces.',
        responsibilities: ['Develop end-to-end Java-based full-stack applications', 'Collaborate with frontend and backend teams on project requirements', 'Implement RESTful APIs and ensure seamless integration', 'Design and develop modern and responsive user interfaces', 'Contribute to code reviews and continuous improvement processes'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in Java full-stack development', 'Expertise in Spring Boot and frontend frameworks like Angular', 'Experience with RESTful APIs and database systems', 'Strong problem-solving and collaboration skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'Enterprise Java Technologies is a leading software development company specializing in end-to-end Java-based solutions. Join our team to contribute to the development of modern and responsive full-stack applications and shape the future of enterprise Java development.',
        company_info: ['https://enterprisejava.tech', '789 Java Street, CodeCity, Bangalore - 560010']
    },
    {
        id: 16,
        image: 'https://img.naukimg.com/logo_images/groups/v1/359414.gif',
        subheading: 'Leading Indian Firm in IT Domain',
        title: 'React.js Developer',
        company_type1: 'Technology Solutions',
        company_type2: 'Service',
        rating: '4.9',
        experiences: '6-10 yrs',
        openings: 22,
        location: 'Delhi',
        skill: ['React.js', 'JavaScript', 'Redux', 'RESTful APIs', 'Webpack', 'HTML/CSS', 'Responsive Web Design'],
        salary: '15-25LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Develop interactive and responsive user interfaces using React.js', 'Collaborate with designers and backend developers on dynamic projects', 'Contribute to building scalable and high-performance web applications'],
        job_description: 'React Innovators Tech is looking for a skilled React.js Developer to join our dynamic team. The ideal candidate will have a strong proficiency in React.js, JavaScript, and state management with Redux. Responsibilities include developing interactive and responsive user interfaces, collaborating with cross-functional teams, and contributing to the creation of scalable and high-performance web applications.',
        responsibilities: ['Develop interactive and responsive user interfaces using React.js', 'Collaborate with designers and backend developers on project requirements', 'Integrate frontend components with RESTful APIs', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in React.js development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in React.js development', 'Expertise in JavaScript and state management with Redux', 'Experience with frontend build tools like Webpack', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'React Innovators Tech is a technology-driven company committed to delivering innovative solutions using React.js. Join our team to contribute to the development of interactive and high-performance web applications and shape the future of React.js development.',
        company_info: ['https://reactinnovators.com', '567 React Street, CodeCity, Delhi - 110012']
    },
    {
        id: 17,
        image: 'https://img.naukri.com/logo_images/v3/3790422.gif',
        subheading: 'Innovations Tech',
        title: 'Senior React Developer',
        company_type1: 'Software Development',
        company_type2: 'Service',
        rating: '4.8',
        experiences: '6-10 yrs',
        openings: 5,
        location: 'Bangalore',
        skill: ['React.js', 'Next.js', 'GraphQL', 'Context API', 'Node.js', 'HTML/CSS', 'Responsive Web Design'],
        salary: '15-25LPA',
        time: '1 day ago',
        job_highlights: ['Job highlights', 'Lead the development of complex React.js applications', 'Collaborate with cross-functional teams on challenging projects', 'Contribute to the implementation of GraphQL for efficient data fetching'],
        job_description: 'React Code Masters is looking for a Senior React Developer to join our experienced team. The ideal candidate will have a deep understanding of React.js, Next.js, and GraphQL, with a focus on leading the development of complex and challenging web applications. Responsibilities include collaborating with cross-functional teams, implementing GraphQL for efficient data fetching, and contributing to the creation of high-performance user interfaces.',
        responsibilities: ['Lead the development of complex React.js applications', 'Collaborate with designers and backend developers on project requirements', 'Implement GraphQL for efficient data fetching', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in React.js and Next.js development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Extensive experience in React.js development', 'Expertise in Next.js and GraphQL', 'Strong understanding of state management with Context API', 'Experience with Node.js for server-side rendering', 'Strong problem-solving and leadership skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'React Code Masters is a software development company known for delivering cutting-edge solutions using React.js. Join our team to lead the development of complex web applications and make a significant impact in the world of React.js development.',
        company_info: ['https://reactcodemasters.com', '789 React Avenue, CodeHub City, Bangalore - 560010']
    },
    {
        id: 18,
        image: 'https://img.naukimg.com/logo_images/groups/v1/1038762.gif',
        subheading: 'Dimension Data',
        title: 'Full Stack Developer (React.js/Node.js)',
        company_type1: 'Technology Solutions',
        company_type2: 'Product',
        rating: '4.9',
        experiences: '0-5 yrs',
        openings: 15,
        location: 'Chennai',
        skill: ['React.js', 'Node.js', 'MongoDB', 'GraphQL', 'Express.js', 'HTML/CSS', 'Responsive Web Design'],
        salary: '0-3LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Work on end-to-end development of full-stack applications', 'Collaborate with cross-functional teams on diverse and challenging projects', 'Contribute to the implementation of GraphQL for efficient data fetching'],
        job_description: 'React Expert Solutions is seeking an experienced Full Stack Developer with expertise in React.js and Node.js to join our dynamic team. The ideal candidate will have a strong background in full-stack development, including frontend technologies, server-side scripting, and database management. Responsibilities include working on the end-to-end development of full-stack applications, collaborating with cross-functional teams, and implementing GraphQL for efficient data fetching.',
        responsibilities: ['Develop end-to-end full-stack applications using React.js and Node.js', 'Collaborate with frontend and backend teams on project requirements', 'Implement GraphQL for efficient data fetching', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in full-stack development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in full-stack development with React.js and Node.js', 'Expertise in MongoDB for database management', 'Experience with GraphQL for efficient data fetching', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime', 'workFromOffice'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'React Expert Solutions is a technology-driven company committed to delivering comprehensive solutions using React.js and Node.js. Join our team to contribute to the development of diverse and challenging full-stack applications and shape the future of technology.',
        company_info: ['https://reactexpertsolutions.com', '567 React Street, CodeCity, Mumbai - 400012']
    },
    {
        id: 19,
        image: 'https://img.naukimg.com/logo_images/groups/v1/1038762.gif',
        subheading: 'Alpha Obs',
        title: 'ANGULAR DEVELOPER',
        company_type1: 'Technology Solutions',
        company_type2: 'Service',
        rating: '4.9',
        experiences: '11-15 yrs',
        openings: 15,
        location: 'Coimbatore',
        skill: ['Angular', 'Node.js', 'MongoDB', 'GraphQL', 'Express.js', 'HTML/CSS', 'Responsive Web Design'],
        salary: '10-15LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Work on end-to-end development of full-stack applications', 'Collaborate with cross-functional teams on diverse and challenging projects', 'Contribute to the implementation of GraphQL for efficient data fetching'],
        job_description: 'React Expert Solutions is seeking an experienced Full Stack Developer with expertise in React.js and Node.js to join our dynamic team. The ideal candidate will have a strong background in full-stack development, including frontend technologies, server-side scripting, and database management. Responsibilities include working on the end-to-end development of full-stack applications, collaborating with cross-functional teams, and implementing GraphQL for efficient data fetching.',
        responsibilities: ['Develop end-to-end full-stack applications using React.js and Node.js', 'Collaborate with frontend and backend teams on project requirements', 'Implement GraphQL for efficient data fetching', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in full-stack development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in full-stack development with React.js and Node.js', 'Expertise in MongoDB for database management', 'Experience with GraphQL for efficient data fetching', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['fullTime', 'partTime', 'workFromHome'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'React Expert Solutions is a technology-driven company committed to delivering comprehensive solutions using React.js and Node.js. Join our team to contribute to the development of diverse and challenging full-stack applications and shape the future of technology.',
        company_info: ['https://reactexpertsolutions.com', '567 React Street, CodeCity, Mumbai - 400012']
    },
    {
        id: 20,
        image: 'https://www.naukri.com/hotjobs/images/v3/Alpha_sept20.gif',
        subheading: 'Indox',
        title: 'Dimension Data',
        company_type1: 'Technology Solutions',
        company_type2: 'Product',
        rating: '4.9',
        experiences: '0-5 yrs',
        openings: 15,
        location: 'Chennai',
        skill: ['Angular', 'Node.js', 'MongoDB', 'GraphQL', 'Express.js', 'HTML/CSS', 'Responsive Web Design'],
        salary: '0-3LPA',
        time: '2 days ago',
        job_highlights: ['Job highlights', 'Work on end-to-end development of full-stack applications', 'Collaborate with cross-functional teams on diverse and challenging projects', 'Contribute to the implementation of GraphQL for efficient data fetching'],
        job_description: 'React Expert Solutions is seeking an experienced Full Stack Developer with expertise in React.js and Node.js to join our dynamic team. The ideal candidate will have a strong background in full-stack development, including frontend technologies, server-side scripting, and database management. Responsibilities include working on the end-to-end development of full-stack applications, collaborating with cross-functional teams, and implementing GraphQL for efficient data fetching.',
        responsibilities: ['Develop end-to-end full-stack applications using React.js and Node.js', 'Collaborate with frontend and backend teams on project requirements', 'Implement GraphQL for efficient data fetching', 'Optimize web applications for maximum speed and scalability', 'Stay updated on emerging trends in full-stack development'],
        requirements: ['Bachelor\'s or Master\'s degree in Computer Science or related field', 'Proven experience in full-stack development with React.js and Node.js', 'Expertise in MongoDB for database management', 'Experience with GraphQL for efficient data fetching', 'Strong problem-solving and teamwork skills'],
        role: "Software Development - Other",
        industryType: "IT Services & Consulting",
        department: "Engineering - Software & QA",
        employmentType: ['workFromOffice', 'workFromHome', 'fullTime', 'partTime'],
        roleCategory: "Software Development",
        education: 'Bachelor\'s or Master\'s degree in Computer Science or related field',
        about_company: 'React Expert Solutions is a technology-driven company committed to delivering comprehensive solutions using React.js and Node.js. Join our team to contribute to the development of diverse and challenging full-stack applications and shape the future of technology.',
        company_info: ['https://reactexpertsolutions.com', '567 React Street, CodeCity, Mumbai - 400012']
    },

]